Cadastro conta bancaria
juliosilvacwb/controlle-financeiro pull request #4
Opened 2021-07-05 22:43 UTC by Thiagohpaes

2021-07-05 23:42 UTC, juliosilvacwb commented
cpf - remover cpf -> cadatro-conta-bancaria.html
incluir campo número do banco
incluir conta/digito no campo conta
incluir campo saldo no cadastro
retirar termo de aceite cadastro de conta

2021-07-05 23:43 UTC, juliosilvacwb requested changes
cpf - remover cpf -> cadatro-conta-bancaria.html
incluir campo número do banco
incluir conta/digito no campo conta
incluir campo saldo no cadastro
retirar termo de aceite cadastro de conta

2021-07-12 03:58 UTC, Thiagohpaes commented
ok

2021-07-12 22:50 UTC, juliosilvacwb approved these changes

2021-07-12 22:50 UTC, merged